### ISSUE TITLE
NOT an Issue!

### ISSUE THREAD

**Issue by nmb4** [icy-lava/sound-maker#1]
I just wanted you to know that this is an awesome tool which also looks fantastic. But I also wanted to let you know that i made something with love2d and some moonscript too and it looks kinda simillar but is very different in terms of usage. Its called LCS, you can take a look at it [here](https://github.com/LogicCircuitSim/LCS/tree/menu-update) (I think the menu-update branch is the most up to date one). I discontinued working on it though, so cant call it up to date really.

Great work though, big probs!

**Comment by icy-lava** [comment]
@ItsNMB Thank you! I just tried your project and wow, it's crazy how similar it looks and feels, and I'm pretty sure I haven't seen it before.
